version: "3.3"

services:
  B:
    image: vincentserpoul/paritypoa:v2.2.1
    ports:
      - "8547:8547"
      - "8548:8548"
      - "30304:30304"
    environment:
      - JSONRPC_PORT=8547
      - WS_PORT=8548
      - NETWORK_PORT=30304
    volumes:
      - chain_B:/home/parity/.local/share/io.parity.ethereum
    secrets:
      - source: authority.B.priv.json
        target: /run/secrets/authority.priv.json
      - source: authority.B.address
        target: /run/secrets/authority.address
      - source: authority.B.password
        target: /run/secrets/authority.password
      - source: validatorsInitSet
        target: /run/secrets/validatorsInitSet
    deploy:
      mode: replicated
      replicas: 1
      labels: [NODE=B]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
        window: 120s
      # service update configuration
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3

volumes:
  chain_B:
    driver_opts:
      o: uid=1000,gid=1000

networks:
  default:
    external:
      name: poa_default

secrets:
  authority.B.priv.json:
    external: true
  authority.B.address:
    external: true
  authority.B.password:
    external: true
  validatorsInitSet:
    external: true
