version: "3.3"

services:
  C:
    image: vincentserpoul/paritypoa:v2.2.1
    ports:
      - "8549:8549"
      - "8550:8550"
      - "30305:30305"
    environment:
      - JSONRPC_PORT=8549
      - WS_PORT=8550
      - NETWORK_PORT=30305
    volumes:
      - chain_C:/home/parity/.local/share/io.parity.ethereum
    secrets:
      - source: authority.C.priv.json
        target: /run/secrets/authority.priv.json
      - source: authority.C.address
        target: /run/secrets/authority.address
      - source: authority.C.password
        target: /run/secrets/authority.password
      - source: validatorsInitSet
        target: /run/secrets/validatorsInitSet
    deploy:
      mode: replicated
      replicas: 1
      labels: [NODE=C]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
        window: 120s
      # service update configuration
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3

volumes:
  chain_C:
    driver_opts:
      o: uid=1000,gid=1000

networks:
  default:
    external:
      name: poa_default

secrets:
  authority.C.priv.json:
    external: true
  authority.C.address:
    external: true
  authority.C.password:
    external: true
  validatorsInitSet:
    external: true
