[parity]
chain = "/home/parity/.poaconfigs/PoA.json"
no_persistent_txqueue = true

[account]
unlock = ["AUTHORITY_ADDRESS"]
password = ["/home/parity/.poasecrets/authority.password"]

[mining]
engine_signer = "AUTHORITY_ADDRESS"
reseal_on_txs = "none"
usd_per_tx = "0"
reseal_max_period = 31536000000

[ui]
interface = "0.0.0.0"
hosts = ["all"]
force = true

[websockets]
interface = "0.0.0.0"
hosts = ["all"]
apis = ["all"]
origins = ["http://127.0.0.1:8180", "http://127.0.0.1:8181", "http://127.0.0.1:8182", "chrome-extension://himekenlppkgeaoeddcliojfddemadig"]

[rpc]
interface = "0.0.0.0"
hosts = ["all"]
cors = ["all"]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub","parity_set", "parity_accounts", "rpc", "shh", "shh_pubsub"]

[misc]
logging = "own_tx,sync=debug"