version: "3.7"

services:
  B:
    image: vincentserpoul/paritypoa:v2.2.2
    ports:
      - "8547:8547"
      - "8548:8548"
      - "30304:30304"
    environment:
      - JSONRPC_PORT=8547
      - WS_PORT=8548
      - NETWORK_PORT=30304
    volumes:
      - chain_B:/home/parity/.local/share/io.parity.ethereum
    configs:
      - source: PoA.json
        target: /home/parity/PoA.json
        uid: "1000"
        gid: "1000"
        mode: 0400
      - source: configPoANode.B.toml
        target: /home/parity/configPoANode.toml
        uid: "1000"
        gid: "1000"
        mode: 0400
      - source: authority.B.address
        target: /home/parity/authority.address
        uid: "1000"
        gid: "1000"
        mode: 0400
    secrets:
      - source: authority.B.priv.json
        target: /run/secrets/authority.priv.json
        uid: "1000"
        gid: "1000"
        mode: 0400
      - source: authority.B.password
        target: /run/secrets/authority.password
        uid: "1000"
        gid: "1000"
        mode: 0400
    deploy:
      mode: replicated
      replicas: 1
      labels: [NODE=A]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
        window: 120s
      # service update configuration
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3

volumes:
  chain_B:
    driver_opts:
      o: rw

configs:
  PoA.json:
    external: true
  configPoANode.B.toml:
    external: true
  authority.B.address:
    external: true

secrets:
  authority.B.priv.json:
    external: true
  authority.B.password:
    external: true
