[parity]
chain = "/etc/parityPoA/PoA.json"
base_path = "/mnt/io.parity.ethereum"

[account]
unlock = ["AUTHORITY_ADDRESS"]
password = ["/run/secrets/authority.AUTHORITY_COMPANY.password"]

[mining]
engine_signer = "AUTHORITY_ADDRESS"
reseal_on_txs = "none"
usd_per_tx = "0"
reseal_max_period = 31536000000

[ui]
interface = "0.0.0.0"
hosts = ["all"]
force = true

[websockets]
interface = "0.0.0.0"
hosts = ["all"]
apis = ["all"]
origins = ["http://127.0.0.1:8180", "http://127.0.0.1:8181", "http://127.0.0.1:8182"]

[rpc]
interface = "0.0.0.0"
hosts = ["all"]
cors = ["all"]
apis = ["all"]

[misc]
logging = "own_tx,sync=debug"