[parity]
chain = "/etc/parityPoA/PoA.json"
base_path = "/mnt/io.parity.ethereum"

[account]
unlock = ["AUTHORITY_ADDRESS"]
password = ["/run/secrets/authority.AUTHORITY_COMPANY.password"]

[mining]
engine_signer = "AUTHORITY_ADDRESS"
reseal_on_txs = "none"
usd_per_tx = "0"

[ui]
force = true
interface = "0.0.0.0"
hosts = ["all"]

[websockets]
interface = "0.0.0.0"
hosts = ["all"]
origins = ["127.0.0.1:8180", "127.0.0.1:8181", "localhost:3000", "chrome-extension://*"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "signer", "personal", "parity_accounts", "parity_set"]

[rpc]
cors = "chrome-extension://*"
# Only selected APIs will be exposed over this interface.
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "signer", "personal", "parity_accounts", "parity_set"]
interface = "0.0.0.0"
hosts = ["all"]