[parity]
chain = "/etc/parityPoA/PoA.json"
base_path = "/mnt/io.parity.ethereum"

[account]
unlock = ["AUTHORITY_ADDRESS"]
password = ["/run/secrets/authority.AUTHORITY_COMPANY.password"]

[mining]
engine_signer = "AUTHORITY_ADDRESS"
reseal_on_txs = "none"
usd_per_tx = "0"
reseal_max_period = 31536000000

[ui]
force = true
interface = "0.0.0.0"
hosts = ["all"]

[websockets]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore"]
interface = "0.0.0.0"
hosts = ["all"]
origins = ["http://127.0.0.1:8180", "http://127.0.0.1:8181", "http://127.0.0.1:8182"]

[rpc]
cors = ["chrome-extension://*"]
# Only selected APIs will be exposed over this interface.
apis = ["all"]
interface = "0.0.0.0"
hosts = ["all"]

[misc]
logging = "own_tx,sync=debug"